# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
gems:
  - jekyll-gist
  - jekyll-feed
gist:
  noscript: false

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            rflog
tagline:          "rfong's computerish journalings"
description:      "computerish journalings"
url:              https://rfong.github.io
baseurl:          /rflog

author:
  name:           'rfong'
  url:            https://rfong.github.io

paginate:         3

# Feed
feed:
  path: feed.xml

# Custom vars
version:          1.0.0

repository:       rfong/rflog
